app/users/models.py
from app import db
from app.users import constants as USER

class User(db.Model):

    __tablename__ = 'users_user'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), unique=True)
    email = db.Column(db.String(120), unique=True)
    password = db.Column(db.String(120))
    role = db.Column(db.SmallInteger, default=USER.USER)
    status = db.Column(db.SmallInteger, default=USER.NEW)

    def __init__(self, name=None, email=None, password=None):
      self.name = name
      self.email = email
      self.password = password

    def getStatus(self):
      return USER.STATUS[self.status]

    def getRole(self):
      return USER.ROLE[self.role]

    def getJSON(self):
      jsonDict = {}
      jsonDict['name'] = self.name
      jsonDict['status'] = self.status

      return jsonDict

    def __repr__(self):
        return '<User %r>' % (self.name)
        

app/users/forms.py
from flask.ext.wtf import Form, RecaptchaField
from wtforms import TextField, PasswordField, BooleanField
from wtforms.validators import Required, EqualTo, Email

class LoginForm(Form):
  email = TextField('Email address', [Required(), Email()])
  password = PasswordField('Password', [Required()])

class RegisterForm(Form):
  name = TextField('NickName', [Required()])
  email = TextField('Email address', [Required(), Email()])
  password = PasswordField('Password', [Required()])
  confirm = PasswordField('Repeat Password', [
      Required(),
      EqualTo('password', message='Passwords must match')
      ])
  accept_tos = BooleanField('I accept the TOS', [Required()])
  # recaptcha = RecaptchaField()

app/users/views.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for
from flask import jsonify
from werkzeug import check_password_hash, generate_password_hash
from pymongo import MongoClient
from app import db
from app.users.forms import RegisterForm, LoginForm
from app.users.models import User
from app.users.decorators import requires_login
from app import mongo
from app import app
from app.decorators import mongoJsonify, jsonResponse
import logging
from app.util import getArgAsList
from logging.handlers import RotatingFileHandler

mod = Blueprint('users', __name__, url_prefix='/users')

@mod.route('/me/')
@requires_login
def home():
  return jsonify(g.user.getJSON())

@mod.before_request
def before_request():
  g.user = None
  if 'user_id' in session:
    g.user = User.query.get(session['user_id'])

@mod.route('/login/', methods=['GET', 'POST'])
def login():
  """
  Login form
  """
  form = LoginForm(request.form)
  if form.validate_on_submit():
    user = User.query.filter_by(email=form.email.data).first()
    if user and check_password_hash(user.password, form.password.data):
      session['user_id'] = user.id
      flash('Welcome %s' % user.name)
      return redirect(url_for('users.home'))
    flash('Wrong email or password', 'error-message')
  return render_template("users/login.html", form=form)

@mod.route('/register/', methods=['GET', 'POST'])
def register():
  """
  Registration Form
  """
  form = RegisterForm(request.form)
  if form.validate_on_submit():
    user = User(name=form.name.data, email=form.email.data, \
      password=generate_password_hash(form.password.data))

    db.session.add(user)
    db.session.commit()

    session['user_id'] = user.id

    flash('Thanks for registering')

    return redirect(url_for('users.home'))
  return render_template("users/register.html", form=form)

@mod.route('/subscribePrice', methods=['GET', 'POST'])
@jsonResponse
def subscribePrice():
  email = getArgAsList(request, 'email')[0]
  productName = getArgAsList(request, 'productName')[0]
  productId = getArgAsList(request, 'productId')[0]
  priceCutOff = getArgAsList(request, 'priceCutOff')[0]
  mongo = MongoClient('localhost', 27017)['userRequests']
  priceSubscribers = mongo.priceSubscribers
  existEntry = priceSubscribers.find_one({'email':email, 'productName':productName,'priceCutOff':priceCutOff,'status':'A'})
  print existEntry
  if not existEntry:
    priceSubscribers.insert({
    "email" : email,
    "productName" : productName,
    "productId" : productId,
    "priceCutOff" : priceCutOff,
    "status" : 'A'
  })
    return True
  else:
    return False

app/templates/users/login.html
{% extends "base.html" %}
{% block content %}
  {% from "forms/macros.html" import render_field %}
  <form method="POST" action="." class="form">
    {{ form.csrf_token }}
    {{ render_field(form.email, class="input text") }}
    {{ render_field(form.password, class="input text") }}
    <input type="submit" value="Login" class="button green">
  </form>
  <a href="{{ url_for('users.register') }}">Register</a>
{% endblock %}

app/templates/users/profile.html
{% extends "base.html" %}
{% block content %}
 Hi {{ user.name }}!
{% endblock %}

app/templates/users/register.html
{% extends "base.html" %}
{% block content %}
  {% from "forms/macros.html" import render_field %}
  <form method="POST" action="." class="form">
    {{ form.csrf_token }}
    {{ render_field(form.name, class="input text") }}
    {{ render_field(form.email, class="input text") }}
    {{ render_field(form.password, class="input text") }}
    {{ render_field(form.confirm, class="input text") }}
    {{ render_field(form.accept_tos, class="input checkbox") }}
    <input type="submit" value="Register" class="button green">
  </form>
  <a href="{{ url_for('users.login') }}">Login</a>
{% endblock %}